"""
Django settings for transcribio project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
import environ
import sys
import smtplib

# Load environment variables
env = environ.Env()
environ.Env.read_env()
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-for-development')
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
CSRF_TRUSTED_ORIGINS = [
    'https://transcripio.com',
    'https://www.transcripio.com',
    'https://transcriptio.applikuapp.com'
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "transcribe_script",
    "accounts",
    'allauth',
    'allauth.account',
    'widget_tweaks',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "transcribio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "transcribio.wsgi.application"

# Database
DATABASES = {
    'default': dj_database_url.parse(env('DATABASE_URL'))
}

# Authentication
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
SITE_ID = 1

# ----------------------------------------------------------------------
# 📧 EMAIL CONFIGURATION
# ----------------------------------------------------------------------
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("DEBUG mode: using console email backend")
else:
    # Required environment variables
    required_env_vars = [
        'MAIL_HOST', 'MAIL_PORT', 'MAIL_USERNAME',
        'MAIL_PASSWORD', 'MAIL_FROM_ADDRESS', 'MAIL_FROM_NAME', 'MAIL_ENCRYPTION'
    ]
    missing_vars = [var for var in required_env_vars if var not in os.environ or not os.environ[var]]
    if missing_vars:
        print(f"ERROR: Missing required email environment variables: {missing_vars}", file=sys.stderr)
        sys.exit(1)

    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ['MAIL_HOST']
    EMAIL_PORT = int(os.environ['MAIL_PORT'])
    EMAIL_HOST_USER = os.environ['MAIL_USERNAME']
    EMAIL_HOST_PASSWORD = os.environ['MAIL_PASSWORD']

    MAIL_ENCRYPTION = os.environ.get('MAIL_ENCRYPTION', 'tls').lower()
    if MAIL_ENCRYPTION == 'ssl':
        EMAIL_USE_SSL = True
        EMAIL_USE_TLS = False
    elif MAIL_ENCRYPTION == 'tls':
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
    else:
        print(f"WARNING: Unrecognized MAIL_ENCRYPTION='{MAIL_ENCRYPTION}', defaulting to TLS", file=sys.stderr)
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False

    DEFAULT_FROM_EMAIL = f"{os.environ.get('MAIL_FROM_NAME')} <{os.environ.get('MAIL_FROM_ADDRESS')}>"
    SERVER_EMAIL = DEFAULT_FROM_EMAIL

    # Test SMTP connection but fall back to console backend if fails
    try:
        if EMAIL_USE_SSL:
            server = smtplib.SMTP_SSL(EMAIL_HOST, EMAIL_PORT, timeout=10)
        else:
            server = smtplib.SMTP(EMAIL_HOST, EMAIL_PORT, timeout=10)
            if EMAIL_USE_TLS:
                server.starttls()
        server.login(EMAIL_HOST_USER, EMAIL_HOST_PASSWORD)
        server.quit()
        print("SMTP test connection successful.")
    except Exception as e:
        print(f"WARNING: Could not connect to SMTP server: {e}", file=sys.stderr)
        print("Falling back to console email backend.")
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ----------------------------------------------------------------------
# 🔐 DJANGO-ALLAUTH SETTINGS
# ----------------------------------------------------------------------
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_SIGNUP_REDIRECT_URL = "/"
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/"
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "/accounts/login/"
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static & Media files
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Ensure media directories exist
os.makedirs(MEDIA_ROOT, mode=0o755, exist_ok=True)
for subdir in ['videos']:
    os.makedirs(os.path.join(MEDIA_ROOT, subdir), mode=0o777, exist_ok=True)

# File upload permissions
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = "/"
