"""
Django settings for transcribio project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
import environ

env = environ.Env()
environ.Env.read_env()
# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-for-development')

# Encryption key for sensitive fields
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://transcripio.com',
    'https://www.transcripio.com',
    'https://transcriptio.applikuapp.com'
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "transcribe_script",
    "accounts",
    'allauth',
    'allauth.account',
    'widget_tweaks',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  
    "django.contrib.sessions.middleware.SessionMiddleware",  
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",  
    "django.contrib.messages.middleware.MessageMiddleware",  
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "transcribio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "transcribio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
'default': dj_database_url.parse(env('DATABASE_URL'))
}

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django Admin, regardless of allauth settings
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]
SITE_ID = 1
# ----------------------------------------------------------------------
# 📧 EMAIL CONFIGURATION
# ----------------------------------------------------------------------

if DEBUG:
    # Development: Print emails to console/terminal
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("Using console email backend (emails will print to terminal)")
else:
    # Production: Use actual SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
    EMAIL_HOST = os.environ.get('MAIL_HOST')
    EMAIL_PORT = int(os.environ.get('MAIL_PORT', 587))
    EMAIL_HOST_USER = os.environ.get('MAIL_USERNAME')
    EMAIL_HOST_PASSWORD = os.environ.get('MAIL_PASSWORD')
    
    MAIL_ENCRYPTION = os.environ.get('MAIL_ENCRYPTION', 'tls').lower()
    if MAIL_ENCRYPTION == 'ssl':
        EMAIL_USE_SSL = True
        EMAIL_USE_TLS = False
    elif MAIL_ENCRYPTION == 'tls':
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
    else:
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False

# These apply to both development and production
DEFAULT_FROM_EMAIL = f"{os.environ.get('MAIL_FROM_NAME', 'Transcriptio')} <{os.environ.get('MAIL_FROM_ADDRESS', 'noreply@transcripio.com')}>"
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# ----------------------------------------------------------------------
# 🔐 DJANGO-ALLAUTH SETTINGS
# ----------------------------------------------------------------------

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Change to optional for now to test
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False  # Since you're using email for auth

# Email confirmation settings
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Redirect URLs
ACCOUNT_SIGNUP_REDIRECT_URL = "/"  # Where to go after signup
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/"  # After email confirmation
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "/accounts/login/"

# Logout settings
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
ACCOUNT_LOGOUT_ON_GET = True

# Important: This tells allauth where to redirect after email is sent
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False  # Only ask for email once
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files - CREATE DIRECTORY WITH PROPER PERMISSIONS
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Create media directory if it doesn't exist and set permissions
try:
    os.makedirs(MEDIA_ROOT, mode=0o755, exist_ok=True)
except Exception as e:
    print(f"Warning: Could not create media directory: {e}")

# File upload permissions
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Redirect to login page when user tries to access protected pages
LOGIN_URL = '/accounts/login/'
# Redirect to upload page after login
LOGIN_REDIRECT_URL = "/"

# Ensure media directories exist with proper permissions
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Create all required subdirectories on startup
import os
for subdir in ['videos']:
    path = os.path.join(MEDIA_ROOT, subdir)
    try:
        os.makedirs(path, mode=0o777, exist_ok=True)
    except Exception as e:
        print(f"Warning: Could not create {path}: {e}")