# Generated by Django 5.2.7 on 2025-10-13 19:21

import transcribe_script.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe_script", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcription",
            name="transcript",
        ),
        migrations.AddField(
            model_name="transcription",
            name="api_key",
            field=models.CharField(
                default=" ", help_text="Your OpenAI API key", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transcription",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="polished_transcript",
            field=models.TextField(blank=True, help_text="Cleaned up by ChatGPT"),
        ),
        migrations.AddField(
            model_name="transcription",
            name="raw_transcript",
            field=models.TextField(blank=True, help_text="Direct output from Whisper"),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="video_file",
            field=models.FileField(
                upload_to="videos/",
                validators=[transcribe_script.models.validate_video_file],
            ),
        ),
    ]
