# Generated by Django 5.2.7 on 2025-10-26 10:11

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe_script", "0003_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                help_text="Your OpenAI API key"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
